/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecommenderRouteImport } from './routes/recommender'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin.quotes'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommenderRoute = RecommenderRouteImport.update({
  id: '/recommender',
  path: '/recommender',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/quote': typeof QuoteRoute
  '/recommender': typeof RecommenderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/quote': typeof QuoteRoute
  '/recommender': typeof RecommenderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/wellness': typeof WellnessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/quote': typeof QuoteRoute
  '/recommender': typeof RecommenderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/wellness': typeof WellnessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/calculator'
    | '/collections'
    | '/contact'
    | '/industries'
    | '/quote'
    | '/recommender'
    | '/sitemap.xml'
    | '/testimonials'
    | '/wellness'
    | '/admin'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/product/$slug'
    | '/blog/'
    | '/collections/'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/industries'
    | '/quote'
    | '/recommender'
    | '/sitemap.xml'
    | '/testimonials'
    | '/wellness'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/product/$slug'
    | '/blog'
    | '/collections'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/calculator'
    | '/collections'
    | '/contact'
    | '/industries'
    | '/quote'
    | '/recommender'
    | '/sitemap.xml'
    | '/testimonials'
    | '/wellness'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/product/$slug'
    | '/blog/'
    | '/collections/'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  QuoteRoute: typeof QuoteRoute
  RecommenderRoute: typeof RecommenderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WellnessRoute: typeof WellnessRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommender': {
      id: '/recommender'
      path: '/recommender'
      fullPath: '/recommender'
      preLoaderRoute: typeof RecommenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  QuoteRoute: QuoteRoute,
  RecommenderRoute: RecommenderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  WellnessRoute: WellnessRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
